name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using codellama."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  OLLAMA_ADDRESS:
    description: "The address of your self deployed ollama service."
    required: true
  LLM_MODEL:
    description: "ollama model."
    required: false
    default: "codellama"
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"